name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['investigate']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what_happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: 'A bug happened!'
    validations:
      required: true
  - type: input
    id: ppnm_version
    attributes:
      label: Pnpm version
      description: What's your pnpm version? (pnpm --version)
      placeholder: '7.1.7'
    validations:
      required: true
  - type: input
    id: node_version
    attributes:
      label: NodeJS version
      description: What's your node version? (node --version)
      placeholder: '16.15.1'
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: input
    id: other_browser
    attributes:
      label: Other browser
      description: If other browser, please specify
      placeholder: Internet Explorer
    validations:
      required: false
  - type: textarea
    id: additional_informations
    attributes:
      label: Any additional information?
      description: If you have more details to give, or even you have an idea of how to fix the problem, please add them here. Any reproduction steps would be appreciated!
      placeholder: You can reproduce the problem by running the following command....
    validations:
      required: false
