name: Feature Report
description: File a feature report
title: '[Feature]: '
labels: ['investigate']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature report!
  - type: textarea
    id: what_idea
    attributes:
      label: What is your idea?
      description: Describe your idea in as much detail as possible.
      placeholder: My awesome idea is to...
    validations:
      required: true
  - type: textarea
    id: additional_informations
    attributes:
      label: Any additional information?
      description: If you have more details to give, some examples, screenshots, or any other information you think would be helpful, please add them here.
    validations:
      required: false
